--liquibase formatted sql
--changeset kemerovqq:1

drop table if exists role;
create table role
(
    role_id int primary key generated by default as identity,
    name    text not null unique
);

insert into role(name)
values ('guest'),
       ('premium_user'),
       ('admin');

drop table if exists client;
create table client
(
    client_id int primary key generated by default as identity,
    username  text unique not null,
    password  text        not null,
    email     text unique not null,
    role      int         not null references role (role_id)
);



