--liquibase formatted sql
--changeset kemerovqq:1

drop table if exists client;
create table client
(
    client_id int primary key generated by default as identity,
    username  text unique not null,
    password  text        not null,
    email     text unique not null,
    role      text not null
);



